### PR TITLE
Add custom color configuration via colors property. fix #78

### LINKED ISSUE #78: Colors in Chrome devtools are too light
localhost 8080 2017-06-27 19-47-55

I feel the colors are too light for Chrome's dev tool when not using the dark theme.

### PR DESCRIPTION
**Pull request by ghost**
As well as a minimal documentation to the default color theme in nanologger.

### CODE REVIEW

**Comment by ghost** [comment]
Hey @yoshuawuyts, I am curious: would you pass the `opts` object directly (maybe for _config_ stuff) or would you rather create a new object à la `{ colors: opts.colors || {} }` explicitly and pass that? Thanks.

Context: https://github.com/yoshuawuyts/nanologger/pull/5

**Comment by yoshuawuyts** [comment]
I reckon the latter (:

**Comment by tgfjt** [comment]
LGTM :tada:

**Comment by tgfjt** [comment]
Released as `v7.1.0`

**Comment by ghost** [comment]
Glad to help out. :)

**Comment by yoshuawuyts** [comment]
woot!

**Pull request merged**
