### PR TITLE
remove example script on package.json

### PR DESCRIPTION
**Pull request by tgfjt**
Hi!
It exists no longer or? :)

### CODE REVIEW

**Comment by toddself** [comment]
Yeah this looks like it was pulled in 524675c2cf02115cd2c637e33b4b2d76e7fb8f54.

**Comment by toddself** [comment]
Looks good to me @tgfjt

**Comment by toddself** [comment]
Perhaps we should replace it with a new example.js though?

**Comment by tgfjt** [comment]
@toddself 
Thanks!
Oh I will create a new example.js! It make sense. 👍

**Comment by tgfjt** [comment]
but people would understand easily with reading README.

**Pull request merged**
